ind_ahor_fin_ult1: Сберегательный счёт
ind_aval_fin_ult1: Банковская гарантия
ind_cco_fin_ult1: Текущие счета
ind_cder_fin_ult1: Деривативный счёт
ind_cno_fin_ult1: Зарплатный проект
ind_ctju_fin_ult1: Детский счёт
ind_ctma_fin_ult1: Особый счёт 3
ind_ctop_fin_ult1: Особый счёт
ind_ctpp_fin_ult1: Особый счёт 2
ind_deco_fin_ult1: Краткосрочный депозит
ind_dela_fin_ult1: Долгосрочный депозит
ind_deme_fin_ult1: Среднесрочный депозит
ind_ecue_fin_ult1: Цифровой счёт
ind_fond_fin_ult1: Денежный средства
ind_hip_fin_ult1: Ипотека
ind_nom_pens_ult1: Выплата пенсионных
ind_nomina_ult1: Выплата зарплаты
ind_plan_fin_ult1: Пенсионный план
ind_pres_fin_ult1: Кредит
ind_reca_fin_ult1: Налоговый счёт
ind_recibo_ult1: Дебетовый аккаунт
ind_tjcr_fin_ult1: Кредитная карта
ind_valo_fin_ult1: Ценные бумаги
ind_viv_fin_ult1: Домашний счёт
