# params.yaml
# Параметры загрузки данных
index_col: "id"
# Параметры обучения модели
target: "price"
one_hot_drop: "if_binary"
iterations: 1000
learning_rate: 0.03
depth: 6
random_state: 42
# Параметры кросс-валидации
# также target
n_splits: 5
n_jobs: -1
metrics: ["neg_root_mean_squared_error", "neg_mean_absolute_percentage_error"]