{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Сервис", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Микросервис", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Время запуска сервиса",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_start_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Общее время CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Файловых дескрипторов",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM сервиса",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Виртуальной памяти",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP запросы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Всего запросов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{instance=\"$instance\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Количество запросов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{instance=\"$instance\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Среднее время обработки запроса",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{instance=\"$instance\"} / http_request_duration_seconds_count{instance=\"$instance\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Ошибок",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{instance=\"$instance\", status!=\"2xx\"})"
    }
   ]
  },
  {
   "title": "Процент ошибок 4xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (handler)(http_requests_total{instance=\"$instance\", status=~\"4.*\", handler!=\"/metrics\"}) / sum by (handler)(http_requests_total{instance=\"$instance\", handler!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Процент ошибок 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler)(http_requests_total{instance=\"$instance\", status=~\"5.*\", path!=\"/metrics\"}) / sum by(handler)(fastapi_responses_total{instance=\"$instance\", path!=\"/metrics\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Время обработки 99% запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{instance=\"$instance\", handler!=\"/metrics\"}[1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Запросы в обработке",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "http_requests_inprogress{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate (http_requests_total{instance=\"$instance\", handler!=\"/metrics\"}[1m])",
     "legendFormat": "{{handler}}({{status}})"
    }
   ]
  },
  { "title": "Предсказания модели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Медиана",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_median{instance=\"$instance\"}",
     "legendFormat": "Модель {{model}}({{results_count}})"
    }
   ]
  },
  {
   "title": "Распределение значений предсказания",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_hist_flats_price_bucket{instance=\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Изменение предсказаний во времени",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "prediction_hist_flats_price_bucket{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}